version: "3"

volumes:
  app:

services:
  uvdesk:
    image: dietermartens/uvdesk
    environment:
      # installation in dev, change it after installation to prod
      - APP_ENV=dev
      - APP_SECRET=
      - TZ=Europe/Brussels
      - APP_TIMEZONE=Europe/Brussels
      - APP_CURRENCY=EUR
      - CRON_USER1=root
      - CRON_SCHEDULE1=*/5 * * * *
      - CRON_COMMAND1=cd /var/www/html && php bin/console uvdesk:refresh-mailbox info@domain.tld support@domain.tld
    restart: always
    extra_hosts:
      - "{uvdesk.domain.tld}:127.0.0.1"
    volumes:
      - app:/var/www/html
